### Basics of Numpy

In [3]:
import numpy as np

In [9]:
# create a single dimension array
a = np.array([1,2,3,5,6,7,8])

In [5]:
print(a)

[1 2 3 5 6 7 8]


In [7]:
a[3]

5

In [8]:
type(a)

numpy.ndarray

In [13]:
## create multidimension array
b = np.array([(1,2,3,5,6,4),(2,3,4,5,6,2),(7,3,1,10,23)])

In [12]:
print(b)

[(1, 2, 3, 5, 6, 4) (2, 3, 4, 5, 6, 2) (7, 3, 1, 10, 23)]


In [14]:
type(b)

numpy.ndarray

In [19]:
c = np.array([(1,2,3,4),(4,5,6,4)])

In [23]:
c

array([[1, 2, 3, 4],
       [4, 5, 6, 4]])

In [24]:
c.ndim

2

In [22]:
c.itemsize

4

In [25]:
c.dtype

dtype('int32')

In [45]:
d = np.array([(1,2,3),(3,4,5),(1,2,4),(4,5,6),(2,4,5)])

In [46]:
d

array([[1, 2, 3],
       [3, 4, 5],
       [1, 2, 4],
       [4, 5, 6],
       [2, 4, 5]])

In [47]:
d.ndim

2

In [48]:
d.shape

(5, 3)

In [49]:
d

array([[1, 2, 3],
       [3, 4, 5],
       [1, 2, 4],
       [4, 5, 6],
       [2, 4, 5]])

In [50]:
d[2]

array([1, 2, 4])

In [51]:
d[1]

array([3, 4, 5])

In [52]:
d[1,1]

4

In [53]:
d[1,2]

5

In [56]:
d[0:4,1]

array([2, 4, 2, 5])

In [55]:
d

array([[1, 2, 3],
       [3, 4, 5],
       [1, 2, 4],
       [4, 5, 6],
       [2, 4, 5]])

In [57]:
e = np.array([[(1,2,3) , (4,5,6)] , [(1,2,3) , (4,5,6)] ])

In [58]:
a

array([1, 2, 3, 5, 6, 7, 8])

In [59]:
e.ndim

3

In [64]:
numbers = np.linspace(1,50,20)

In [65]:
numbers

array([ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947,
       13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632,
       26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316,
       39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ])

In [66]:
numbers.min()

1.0

In [67]:
numbers.max()

50.0

In [68]:
numbers.sum()

510.0

In [72]:
numbers.mean()

25.5

In [74]:
g = np.array([(1,2,4),(2,3,6)])
g

array([[1, 2, 4],
       [2, 3, 6]])

In [75]:
g.sum()

18

In [76]:
g.sum(axis=0)

array([ 3,  5, 10])

In [77]:
g.sum(axis=1)

array([ 7, 11])

In [78]:
# Concatination of arrays
# vertical stacking
# horizontal stacking

In [79]:
i = np.array([(1,2,4),(4,5,6)])
j = np.array([(10,20,40),(40,50,60)])

In [81]:
# vertical stacking
np.vstack((i,j))

array([[ 1,  2,  4],
       [ 4,  5,  6],
       [10, 20, 40],
       [40, 50, 60]])

In [82]:
# horizontal stacking
np.hstack((i,j))

array([[ 1,  2,  4, 10, 20, 40],
       [ 4,  5,  6, 40, 50, 60]])

In [87]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [88]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [89]:
np.ones((5,5))*200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

In [93]:
np.random.randint(0,100)

30

In [97]:
np.random.randint(0,100,10)

array([70,  2, 84, 55, 41, 59,  5, 13, 28, 89])

In [105]:
np.random.seed(100)
np.random.randint(0,100,10)

array([ 8, 24, 67, 87, 79, 48, 10, 94, 52, 98])

In [1]:
import numpy as np

In [2]:
a = np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])

In [3]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [5]:
a.ndim

3